### Importing NumPy

In [3]:
import numpy as np
print(np.__version__)

2.4.6


In [4]:
# Basic 1D array multiplication

array = np.array([1, 2, 3, 4, 5])
array *= 2
print(array)

[ 2  4  6  8 10]


### Creating multi-dimentional arrays

In [5]:
# 1D array

array = np.array([ 'A', 'B', 'C' ])

print(array.ndim)
print(array.shape)

1
(3,)


In [6]:
# 2D array

array = np.array([[ 'A', 'B', 'C', 'D'],
                  [ 'E', 'F', 'G', 'H'],
                  [ 'I', 'J', 'K', 'L'],
                  [ 'M', 'N', 'O', 'P']])

print(array.ndim)
print(array.shape)


2
(4, 4)


In [7]:
# 3D array

# array = np.array([[[ 'A', 'B', 'C', 'D'],
#                   [ 'E', 'F', 'G', 'H'],
#                   [ 'I', 'J', 'K', 'L'],
#                   [ 'M', 'N', 'O', 'P']]])

array = np.array([[[ 'A', 'B', 'C', 'D']],
                  [[ 'E', 'F', 'G', 'H']],
                  [[ 'I', 'J', 'K', 'L']],
                  [['M', 'N', 'O', 'P']]])

print(array.ndim)
print(array.shape)


3
(4, 1, 4)


In [8]:
# 4D array

array = np.array([[[[ 'A', 'B', 'C', 'D'],
                  [ 'E', 'F', 'G', 'H'],
                  [ 'I', 'J', 'K', 'L'],
                  [ 'M', 'N', 'O', 'P']]]])

print(array.ndim)
print(array.shape)

4
(1, 1, 4, 4)


### Multi-dimentional Indexing and printing words from array

In [9]:
array = np.array([[[ 'A', 'B', 'C', 'D']],
                  [[ 'E', 'F', 'G', 'H']],
                  [[ 'I', 'J', 'K', 'L']],
                  [['M', 'N', 'O', 'P']]])

print(array.ndim)
print("\n")
print(array.shape)
print("\n")


print(array[0, 0, 0])
print(array[0, 0, 1])
print(array[0, 0, 2])
print(array[0, 0, 3])

print(array[1, 0, 0])
print(array[1, 0, 1])
print(array[1, 0, 2])
print(array[1, 0, 3])

print(array[2, 0, 0])
print(array[2, 0, 1])
print(array[2, 0, 2])
print(array[2, 0, 3])

print(array[3, 0, 0])
print(array[3, 0, 1])
print(array[3, 0, 2])
print(array[3, 0, 3])

print("\n")
word = array[1, 0, 0] +array[1, 0, 2] + array[1, 0, 2]
print(word)


3


(4, 1, 4)


A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P


EGG


In [10]:
array = np.array([[[ 'A', 'B', 'C', 'D'],
                  [ 'E', 'F', 'G', 'H'],
                  [ 'I', 'J', 'K', 'L'],
                  [ 'M', 'N', 'O', 'P']]])

print(array.ndim)
print("\n")
print(array.shape)
print("\n")


print(array[0, 0, 0]) 
print(array[0, 0, 1])
print(array[0, 0, 2])
print(array[0, 0, 3])

print(array[0, 1, 0])
print(array[0, 1, 1])
print(array[0, 1, 2])
print(array[0, 1, 3])

print(array[0, 2, 0])
print(array[0, 2, 1])
print(array[0, 2, 2])
print(array[0, 2, 3])

print(array[0, 3, 0])
print(array[0, 3, 1])
print(array[0, 3, 2])
print(array[0, 3, 3])

print("\n")
word = array[0, 1, 0] + array[0, 1, 2] + array[0, 1, 2]
print(word)


3


(1, 4, 4)


A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P


EGG


### SLICING

#### Row Slicing

In [11]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# print(array)

# Positive Indexing (START)
print(array[0])
print("\n")
print(array[1])
print("\n")
print(array[2])
print("\n")
print(array[3])
print("\n")

# Negative Indexing (START)
print(array[-1])
print("\n")
print(array[-2])
print("\n")
print(array[-3])
print("\n")
print(array[-4])
print("\n")

# Using (START : END )
print(array[0:3])
print("\n")
print(array[3:0])
print("\n")
print(array[2:2])
print("\n")
print(array[-4:-1])
print("\n")

# Using (START : END : STEP )
print(array[0:4:2])
print("\n")
print(array[::-2])
print("\n")
print(array[-4:-1:2])
print("\n")

[1 2 3 4]


[5 6 7 8]


[ 9 10 11 12]


[13 14 15 16]


[13 14 15 16]


[ 9 10 11 12]


[5 6 7 8]


[1 2 3 4]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[]


[]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 1  2  3  4]
 [ 9 10 11 12]]


[[13 14 15 16]
 [ 5  6  7  8]]


[[ 1  2  3  4]
 [ 9 10 11 12]]




#### Column Slicing

In [12]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

# Single Column Slicing
print(array[:,0])
print("\n")
print(array[:,1])
print("\n")
print(array[:,3])
print("\n")
print(array[:,-1])
print("\n")
print(array[:,-4])

# Multi column Slicing
print("\n")
print(array[:,0:3])
print("\n")
print(array[:,::2])
print("\n")
print(array[:,1::2])
print("\n")
print(array[:,::-2])



[ 1  5  9 13]


[ 2  6 10 14]


[ 4  8 12 16]


[ 4  8 12 16]


[ 1  5  9 13]


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


#### Row and Column slicing

In [ ]:
# These 2 are same
print(array[:2,:2])
print("\n")
print(array[0:2,0:2])
print("\n")

# These 2 are same
print(array[0:2,2:])
print("\n")
print(array[0:2,2:4])
print("\n")

# These 2 are same
print(array[2:,:2])
print("\n")
print(array[2:4,0:2])
print("\n")

# These 2 are same
print(array[2:,2:])
print("\n")
print(array[2:4,2:4])


### Arithmetic Operations

In [16]:
# Scalar Arithmetic

array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [18]:
# Vectorized Math Functions

array = np.array([1, 2, 3])
print(np.sqrt(array))
array = np.array([1.01, 2.5, 3.99])
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)

[1.         1.41421356 1.73205081]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [19]:
# Calculating the area of a circle

radius = np.array([1, 2, 3])
print(np.pi * radius ** 2)

[ 3.14159265 12.56637061 28.27433388]
